#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITCindex")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertloginNum(loginNum instance);
  partial void UpdateloginNum(loginNum instance);
  partial void DeleteloginNum(loginNum instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ITCindexConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<loginNum> loginNum
	{
		get
		{
			return this.GetTable<loginNum>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginNum")]
public partial class loginNum : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _LoginNumID;
	
	private string _SystemType;
	
	private System.Nullable<System.DateTime> _LoginDate;
	
	private string _LoginID;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginNumIDChanging(int value);
    partial void OnLoginNumIDChanged();
    partial void OnSystemTypeChanging(string value);
    partial void OnSystemTypeChanged();
    partial void OnLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoginDateChanged();
    partial void OnLoginIDChanging(string value);
    partial void OnLoginIDChanged();
    #endregion
	
	public loginNum()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginNumID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int LoginNumID
	{
		get
		{
			return this._LoginNumID;
		}
		set
		{
			if ((this._LoginNumID != value))
			{
				this.OnLoginNumIDChanging(value);
				this.SendPropertyChanging();
				this._LoginNumID = value;
				this.SendPropertyChanged("LoginNumID");
				this.OnLoginNumIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemType", DbType="VarChar(10)")]
	public string SystemType
	{
		get
		{
			return this._SystemType;
		}
		set
		{
			if ((this._SystemType != value))
			{
				this.OnSystemTypeChanging(value);
				this.SendPropertyChanging();
				this._SystemType = value;
				this.SendPropertyChanged("SystemType");
				this.OnSystemTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> LoginDate
	{
		get
		{
			return this._LoginDate;
		}
		set
		{
			if ((this._LoginDate != value))
			{
				this.OnLoginDateChanging(value);
				this.SendPropertyChanging();
				this._LoginDate = value;
				this.SendPropertyChanged("LoginDate");
				this.OnLoginDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="NVarChar(100)")]
	public string LoginID
	{
		get
		{
			return this._LoginID;
		}
		set
		{
			if ((this._LoginID != value))
			{
				this.OnLoginIDChanging(value);
				this.SendPropertyChanging();
				this._LoginID = value;
				this.SendPropertyChanged("LoginID");
				this.OnLoginIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
