<?xml version="1.0" encoding="utf-8"?><Database Name="ITCindex" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KAI-PC\SQLEXPRESS;Initial Catalog=ITCindex;User ID=talll" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ITCindexConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.loginNum" Member="loginNum">
    <Type Name="loginNum">
      <Column Name="LoginNumID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SystemType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>