#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UTCS_Base_KS")]
public partial class DataClasses3DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  #endregion
	
	public DataClasses3DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["UTCS_Base_KSConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ETAG_INFO> ETAG_INFO
	{
		get
		{
			return this.GetTable<ETAG_INFO>();
		}
	}
	
	public System.Data.Linq.Table<ETAG_RECEIVED_COMMAND> ETAG_RECEIVED_COMMAND
	{
		get
		{
			return this.GetTable<ETAG_RECEIVED_COMMAND>();
		}
	}
	
	public System.Data.Linq.Table<ETAG_SECTORTAB> ETAG_SECTORTAB
	{
		get
		{
			return this.GetTable<ETAG_SECTORTAB>();
		}
	}
	
	public System.Data.Linq.Table<ETAGTAB> ETAGTAB
	{
		get
		{
			return this.GetTable<ETAGTAB>();
		}
	}
	
	public System.Data.Linq.Table<ETAG_VEHICLE> ETAG_VEHICLE
	{
		get
		{
			return this.GetTable<ETAG_VEHICLE>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAG_INFO")]
public partial class ETAG_INFO
{
	
	private string _etagid;
	
	private string _locationpath;
	
	private string _startlocationpoint;
	
	private string _endlocationpoint;
	
	private string _roadsection;
	
	private System.Nullable<double> _px;
	
	private System.Nullable<double> _py;
	
	private string _roadname;
	
	private string _id;
	
	private string _DES;
	
	public ETAG_INFO()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etagid", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string etagid
	{
		get
		{
			return this._etagid;
		}
		set
		{
			if ((this._etagid != value))
			{
				this._etagid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locationpath", DbType="NVarChar(5)")]
	public string locationpath
	{
		get
		{
			return this._locationpath;
		}
		set
		{
			if ((this._locationpath != value))
			{
				this._locationpath = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startlocationpoint", DbType="NVarChar(5)")]
	public string startlocationpoint
	{
		get
		{
			return this._startlocationpoint;
		}
		set
		{
			if ((this._startlocationpoint != value))
			{
				this._startlocationpoint = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endlocationpoint", DbType="NVarChar(5)")]
	public string endlocationpoint
	{
		get
		{
			return this._endlocationpoint;
		}
		set
		{
			if ((this._endlocationpoint != value))
			{
				this._endlocationpoint = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roadsection", DbType="NVarChar(50)")]
	public string roadsection
	{
		get
		{
			return this._roadsection;
		}
		set
		{
			if ((this._roadsection != value))
			{
				this._roadsection = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_px", DbType="Float")]
	public System.Nullable<double> px
	{
		get
		{
			return this._px;
		}
		set
		{
			if ((this._px != value))
			{
				this._px = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_py", DbType="Float")]
	public System.Nullable<double> py
	{
		get
		{
			return this._py;
		}
		set
		{
			if ((this._py != value))
			{
				this._py = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roadname", DbType="NVarChar(50)")]
	public string roadname
	{
		get
		{
			return this._roadname;
		}
		set
		{
			if ((this._roadname != value))
			{
				this._roadname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DES", DbType="NVarChar(10)")]
	public string DES
	{
		get
		{
			return this._DES;
		}
		set
		{
			if ((this._DES != value))
			{
				this._DES = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAG_RECEIVED_COMMAND")]
public partial class ETAG_RECEIVED_COMMAND
{
	
	private string _NO;
	
	private System.Nullable<System.DateTime> _DateTime;
	
	private string _Code;
	
	private string _CommandID;
	
	private string _DeviceID;
	
	private string _VehicleID;
	
	private string _VehicleNO;
	
	private string _Year;
	
	private string _Month;
	
	private string _Day;
	
	private string _Hour;
	
	private string _Min;
	
	private string _Sec;
	
	private string _Week;
	
	private string _VehicleIDCycle;
	
	private string _VehicleNOCycle;
	
	private string _ErrorCode;
	
	private string _ParameterNumber;
	
	private string _SecDif;
	
	private string _HardwareStatus;
	
	private string _Reset;
	
	private string _EquipmentNO;
	
	private string _SubCount;
	
	private string _SubEquipmentNO;
	
	private string _EquipmentID;
	
	private string _CompanyID;
	
	private string _Version;
	
	private string _CommandSet;
	
	private string _HardwareCycle;
	
	public ETAG_RECEIVED_COMMAND()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", DbType="NVarChar(20)")]
	public string NO
	{
		get
		{
			return this._NO;
		}
		set
		{
			if ((this._NO != value))
			{
				this._NO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateTime
	{
		get
		{
			return this._DateTime;
		}
		set
		{
			if ((this._DateTime != value))
			{
				this._DateTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(8)")]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this._Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommandID", DbType="NVarChar(8)")]
	public string CommandID
	{
		get
		{
			return this._CommandID;
		}
		set
		{
			if ((this._CommandID != value))
			{
				this._CommandID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceID", DbType="NVarChar(8)")]
	public string DeviceID
	{
		get
		{
			return this._DeviceID;
		}
		set
		{
			if ((this._DeviceID != value))
			{
				this._DeviceID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleID", DbType="NVarChar(24)")]
	public string VehicleID
	{
		get
		{
			return this._VehicleID;
		}
		set
		{
			if ((this._VehicleID != value))
			{
				this._VehicleID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNO", DbType="NVarChar(10)")]
	public string VehicleNO
	{
		get
		{
			return this._VehicleNO;
		}
		set
		{
			if ((this._VehicleNO != value))
			{
				this._VehicleNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(5)")]
	public string Year
	{
		get
		{
			return this._Year;
		}
		set
		{
			if ((this._Year != value))
			{
				this._Year = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(4)")]
	public string Month
	{
		get
		{
			return this._Month;
		}
		set
		{
			if ((this._Month != value))
			{
				this._Month = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="NVarChar(4)")]
	public string Day
	{
		get
		{
			return this._Day;
		}
		set
		{
			if ((this._Day != value))
			{
				this._Day = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="NVarChar(4)")]
	public string Hour
	{
		get
		{
			return this._Hour;
		}
		set
		{
			if ((this._Hour != value))
			{
				this._Hour = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Min", DbType="NVarChar(4)")]
	public string Min
	{
		get
		{
			return this._Min;
		}
		set
		{
			if ((this._Min != value))
			{
				this._Min = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sec", DbType="NVarChar(4)")]
	public string Sec
	{
		get
		{
			return this._Sec;
		}
		set
		{
			if ((this._Sec != value))
			{
				this._Sec = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Week", DbType="NVarChar(4)")]
	public string Week
	{
		get
		{
			return this._Week;
		}
		set
		{
			if ((this._Week != value))
			{
				this._Week = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleIDCycle", DbType="NVarChar(4)")]
	public string VehicleIDCycle
	{
		get
		{
			return this._VehicleIDCycle;
		}
		set
		{
			if ((this._VehicleIDCycle != value))
			{
				this._VehicleIDCycle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNOCycle", DbType="NVarChar(4)")]
	public string VehicleNOCycle
	{
		get
		{
			return this._VehicleNOCycle;
		}
		set
		{
			if ((this._VehicleNOCycle != value))
			{
				this._VehicleNOCycle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="NVarChar(4)")]
	public string ErrorCode
	{
		get
		{
			return this._ErrorCode;
		}
		set
		{
			if ((this._ErrorCode != value))
			{
				this._ErrorCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParameterNumber", DbType="NVarChar(4)")]
	public string ParameterNumber
	{
		get
		{
			return this._ParameterNumber;
		}
		set
		{
			if ((this._ParameterNumber != value))
			{
				this._ParameterNumber = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecDif", DbType="NVarChar(4)")]
	public string SecDif
	{
		get
		{
			return this._SecDif;
		}
		set
		{
			if ((this._SecDif != value))
			{
				this._SecDif = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HardwareStatus", DbType="NVarChar(4)")]
	public string HardwareStatus
	{
		get
		{
			return this._HardwareStatus;
		}
		set
		{
			if ((this._HardwareStatus != value))
			{
				this._HardwareStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reset", DbType="NVarChar(4)")]
	public string Reset
	{
		get
		{
			return this._Reset;
		}
		set
		{
			if ((this._Reset != value))
			{
				this._Reset = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentNO", DbType="NVarChar(4)")]
	public string EquipmentNO
	{
		get
		{
			return this._EquipmentNO;
		}
		set
		{
			if ((this._EquipmentNO != value))
			{
				this._EquipmentNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCount", DbType="NVarChar(4)")]
	public string SubCount
	{
		get
		{
			return this._SubCount;
		}
		set
		{
			if ((this._SubCount != value))
			{
				this._SubCount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubEquipmentNO", DbType="NVarChar(4)")]
	public string SubEquipmentNO
	{
		get
		{
			return this._SubEquipmentNO;
		}
		set
		{
			if ((this._SubEquipmentNO != value))
			{
				this._SubEquipmentNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentID", DbType="NVarChar(4)")]
	public string EquipmentID
	{
		get
		{
			return this._EquipmentID;
		}
		set
		{
			if ((this._EquipmentID != value))
			{
				this._EquipmentID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="NVarChar(4)")]
	public string CompanyID
	{
		get
		{
			return this._CompanyID;
		}
		set
		{
			if ((this._CompanyID != value))
			{
				this._CompanyID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(4)")]
	public string Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this._Version = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommandSet", DbType="NVarChar(4)")]
	public string CommandSet
	{
		get
		{
			return this._CommandSet;
		}
		set
		{
			if ((this._CommandSet != value))
			{
				this._CommandSet = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HardwareCycle", DbType="NVarChar(4)")]
	public string HardwareCycle
	{
		get
		{
			return this._HardwareCycle;
		}
		set
		{
			if ((this._HardwareCycle != value))
			{
				this._HardwareCycle = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAG_SECTORTAB")]
public partial class ETAG_SECTORTAB
{
	
	private string _SECTORID;
	
	private string _SECTORNAME;
	
	private string _STARTIC;
	
	private string _ENDIC;
	
	private System.Nullable<double> _LENGTH;
	
	private System.Nullable<double> _LANENO;
	
	private string _INTDIR;
	
	private string _GROUPID;
	
	private System.Nullable<double> _LANELENGTH;
	
	private string _MODEL;
	
	private string _CMSDESC;
	
	private string _STATUS;
	
	private System.Nullable<double> _TRAVELTIME;
	
	private System.Nullable<double> _CAPACITY;
	
	public ETAG_SECTORTAB()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTORID", DbType="NVarChar(255)")]
	public string SECTORID
	{
		get
		{
			return this._SECTORID;
		}
		set
		{
			if ((this._SECTORID != value))
			{
				this._SECTORID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTORNAME", DbType="NVarChar(255)")]
	public string SECTORNAME
	{
		get
		{
			return this._SECTORNAME;
		}
		set
		{
			if ((this._SECTORNAME != value))
			{
				this._SECTORNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTIC", DbType="NVarChar(255)")]
	public string STARTIC
	{
		get
		{
			return this._STARTIC;
		}
		set
		{
			if ((this._STARTIC != value))
			{
				this._STARTIC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDIC", DbType="NVarChar(255)")]
	public string ENDIC
	{
		get
		{
			return this._ENDIC;
		}
		set
		{
			if ((this._ENDIC != value))
			{
				this._ENDIC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LENGTH", DbType="Float")]
	public System.Nullable<double> LENGTH
	{
		get
		{
			return this._LENGTH;
		}
		set
		{
			if ((this._LENGTH != value))
			{
				this._LENGTH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANENO", DbType="Float")]
	public System.Nullable<double> LANENO
	{
		get
		{
			return this._LANENO;
		}
		set
		{
			if ((this._LANENO != value))
			{
				this._LANENO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTDIR", DbType="NVarChar(255)")]
	public string INTDIR
	{
		get
		{
			return this._INTDIR;
		}
		set
		{
			if ((this._INTDIR != value))
			{
				this._INTDIR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPID", DbType="NVarChar(255)")]
	public string GROUPID
	{
		get
		{
			return this._GROUPID;
		}
		set
		{
			if ((this._GROUPID != value))
			{
				this._GROUPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANELENGTH", DbType="Float")]
	public System.Nullable<double> LANELENGTH
	{
		get
		{
			return this._LANELENGTH;
		}
		set
		{
			if ((this._LANELENGTH != value))
			{
				this._LANELENGTH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODEL", DbType="NVarChar(255)")]
	public string MODEL
	{
		get
		{
			return this._MODEL;
		}
		set
		{
			if ((this._MODEL != value))
			{
				this._MODEL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMSDESC", DbType="NVarChar(255)")]
	public string CMSDESC
	{
		get
		{
			return this._CMSDESC;
		}
		set
		{
			if ((this._CMSDESC != value))
			{
				this._CMSDESC = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(255)")]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this._STATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAVELTIME", DbType="Float")]
	public System.Nullable<double> TRAVELTIME
	{
		get
		{
			return this._TRAVELTIME;
		}
		set
		{
			if ((this._TRAVELTIME != value))
			{
				this._TRAVELTIME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Float")]
	public System.Nullable<double> CAPACITY
	{
		get
		{
			return this._CAPACITY;
		}
		set
		{
			if ((this._CAPACITY != value))
			{
				this._CAPACITY = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAGTAB")]
public partial class ETAGTAB
{
	
	private string _ETAGID;
	
	private string _ETAGNAME;
	
	private string _SECTORID;
	
	private string _GROUPID;
	
	private string _REGIONID;
	
	private string _SECTORVOL;
	
	private string _SNWIDTH;
	
	private string _WEWIDTH;
	
	private string _STATUS;
	
	private string _DIRECTION;
	
	private string _OICID;
	
	private string _GISX;
	
	private string _GISY;
	
	public ETAGTAB()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETAGID", DbType="NVarChar(255)")]
	public string ETAGID
	{
		get
		{
			return this._ETAGID;
		}
		set
		{
			if ((this._ETAGID != value))
			{
				this._ETAGID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETAGNAME", DbType="NVarChar(255)")]
	public string ETAGNAME
	{
		get
		{
			return this._ETAGNAME;
		}
		set
		{
			if ((this._ETAGNAME != value))
			{
				this._ETAGNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTORID", DbType="NVarChar(255)")]
	public string SECTORID
	{
		get
		{
			return this._SECTORID;
		}
		set
		{
			if ((this._SECTORID != value))
			{
				this._SECTORID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPID", DbType="NVarChar(255)")]
	public string GROUPID
	{
		get
		{
			return this._GROUPID;
		}
		set
		{
			if ((this._GROUPID != value))
			{
				this._GROUPID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGIONID", DbType="NVarChar(255)")]
	public string REGIONID
	{
		get
		{
			return this._REGIONID;
		}
		set
		{
			if ((this._REGIONID != value))
			{
				this._REGIONID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTORVOL", DbType="NVarChar(255)")]
	public string SECTORVOL
	{
		get
		{
			return this._SECTORVOL;
		}
		set
		{
			if ((this._SECTORVOL != value))
			{
				this._SECTORVOL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNWIDTH", DbType="NVarChar(255)")]
	public string SNWIDTH
	{
		get
		{
			return this._SNWIDTH;
		}
		set
		{
			if ((this._SNWIDTH != value))
			{
				this._SNWIDTH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEWIDTH", DbType="NVarChar(255)")]
	public string WEWIDTH
	{
		get
		{
			return this._WEWIDTH;
		}
		set
		{
			if ((this._WEWIDTH != value))
			{
				this._WEWIDTH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(255)")]
	public string STATUS
	{
		get
		{
			return this._STATUS;
		}
		set
		{
			if ((this._STATUS != value))
			{
				this._STATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECTION", DbType="NChar(10)")]
	public string DIRECTION
	{
		get
		{
			return this._DIRECTION;
		}
		set
		{
			if ((this._DIRECTION != value))
			{
				this._DIRECTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OICID", DbType="VarChar(5)")]
	public string OICID
	{
		get
		{
			return this._OICID;
		}
		set
		{
			if ((this._OICID != value))
			{
				this._OICID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GISX", DbType="VarChar(10)")]
	public string GISX
	{
		get
		{
			return this._GISX;
		}
		set
		{
			if ((this._GISX != value))
			{
				this._GISX = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GISY", DbType="VarChar(10)")]
	public string GISY
	{
		get
		{
			return this._GISY;
		}
		set
		{
			if ((this._GISY != value))
			{
				this._GISY = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ETAG_VEHICLE")]
public partial class ETAG_VEHICLE
{
	
	private string _DEVICEID;
	
	private System.DateTime _RECEIVEDATE;
	
	private string _LANEID;
	
	private string _PLATEID;
	
	public ETAG_VEHICLE()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEVICEID", DbType="VarChar(7)")]
	public string DEVICEID
	{
		get
		{
			return this._DEVICEID;
		}
		set
		{
			if ((this._DEVICEID != value))
			{
				this._DEVICEID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVEDATE", DbType="DateTime")]
	public System.DateTime RECEIVEDATE
	{
		get
		{
			return this._RECEIVEDATE;
		}
		set
		{
			if ((this._RECEIVEDATE != value))
			{
				this._RECEIVEDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANEID", DbType="VarChar(1)")]
	public string LANEID
	{
		get
		{
			return this._LANEID;
		}
		set
		{
			if ((this._LANEID != value))
			{
				this._LANEID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLATEID", DbType="VarChar(24)")]
	public string PLATEID
	{
		get
		{
			return this._PLATEID;
		}
		set
		{
			if ((this._PLATEID != value))
			{
				this._PLATEID = value;
			}
		}
	}
}
#pragma warning restore 1591
